---
- hosts: test01
  become: yes
  vars:
    loki_install: true
    loki_host: test01   # для Promtail на других серверах
  roles:
    - role: fill.loki

- hosts: all
  become: yes
  vars:
    promtail_install: true
    loki_host: test01   # указываем, где Loki
  roles:
    - role: fill.loki
